=== osgi/osgi/xmlns/metatype/metatype.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	/*
	* $Header$
	* 
	* Copyright (c) OSGi Alliance (2005, 2006). All Rights Reserved.
	* 
	* This program and the accompanying materials are made available under the
	* terms of the Eclipse Public License v1.0 which accompanies this 
	* distribution, and is available at http://www.eclipse.org/legal/epl-v10.html.
	*/
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.osgi.org/xmlns/metatype/v1.0.0"
	xmlns:metatype="http://www.osgi.org/xmlns/metatype/v1.0.0">

	<complexType name="MetaData">
		<sequence>
			<element name="OCD" type="metatype:OCD" minOccurs="0"
				maxOccurs="unbounded" />
			<element name="Designate" type="metatype:Designate"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="localization" type="string" use="optional" />
	</complexType>

	<complexType name="OCD">
		<sequence>
			<element name="AD" type="metatype:AD" minOccurs="1"
				maxOccurs="unbounded" />
			<element name="Icon" type="metatype:Icon" minOccurs="0"
				maxOccurs="1" />
		</sequence>
		<attribute name="name" type="string" use="required" />
		<attribute name="description" type="string" use="optional" />
		<attribute name="id" type="string" use="required" />
	</complexType>

	<complexType name="AD">
		<sequence>
			<element name="Option" type="metatype:Option" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" use="optional" />
		<attribute name="description" type="string" use="optional" />
		<attribute name="id" type="string" use="required" />
		<attribute name="type" type="metatype:Scalar" use="required" />
		<attribute name="cardinality" type="int" use="optional"
			default="0" />
		<attribute name="min" type="string" use="optional" />
		<attribute name="max" type="string" use="optional" />
		<attribute name="default" type="string" use="optional" />
		<attribute name="required" type="boolean" use="optional"
			default="true" />
	</complexType>

	<complexType name="Object">
		<sequence>
			<element name="Attribute" type="metatype:Attribute"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="ocdref" type="string" use="required" />
	</complexType>

	<complexType name="Attribute">
		<sequence>
			<element name="Value" type="string" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
		<attribute name="adref" type="string" use="required" />
		<attribute name="content" type="string" use="optional" />
	</complexType>

	<complexType name="Designate">
		<sequence>
			<element name="Object" type="metatype:Object" minOccurs="1"
				maxOccurs="1" />
		</sequence>
		<attribute name="pid" type="string" use="required" />
		<attribute name="factoryPid" type="string" use="optional" />
		<attribute name="bundle" type="string" use="required" />
		<attribute name="optional" type="boolean" default="false"
			use="optional" />
		<attribute name="merge" type="boolean" default="false"
			use="optional" />
	</complexType>

	<simpleType name="Scalar">
		<restriction base="string">
			<enumeration value="String" />
			<enumeration value="Long" />
			<enumeration value="Double" />
			<enumeration value="Float" />
			<enumeration value="Integer" />
			<enumeration value="Byte" />
			<enumeration value="Char" />
			<enumeration value="Boolean" />
			<enumeration value="Short" />
		</restriction>
	</simpleType>

	<complexType name="Option">
		<attribute name="label" type="string" use="required" />
		<attribute name="value" type="string" use="required" />
	</complexType>

	<complexType name="Icon">
		<attribute name="resource" type="string" use="required" />
		<attribute name="size" type="positiveInteger" use="required" />
	</complexType>

	<element name="MetaData" type="metatype:MetaData" />
</schema>

=== osgi/osgi/archive/org.osgi.test.cases.metatype2/tb1/testfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<md:MetaData xmlns:md="http://www.org.osgi/xmlns/metatype/v1.0.0/md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.org.osgi/xmlns/metatype/v1.0.0/md
 metatype.xsd">
	<OCD id="ocd1" name="%Person" description="%Description">
		<AD  id="surName" name="%Surname" type="String" max="24" min="2" default="" required="true"/>
		<AD  id="sex" name="%Sex" type="String" default="" description="%SexDescription" required="false">
			<Option label="%Male" value="male"/>
			<Option label="%Female" value="female"/>
			<Option label="%Yes" value="yes"/>
			<Option label="%No" value="no"/>
		</AD>
		<AD id="familyName" name="%FamilyName" type="String" default="" required="true"/>
		<AD id="age" name="%Age" type="Integer" min="13" max="120" default="18" required="false"/>
		<Icon resource="%Icon" size="16"/>
	</OCD>
	
	<OCD id="ocd2" name="%Object" description="%Description">
		<AD id="boolean" name="%Boolean" type="Boolean" default="false"/>
		<AD id="byte" name="%Byte" type="Byte" default="0"/>
		<AD id="character" name="%Character" type="Char" default="0"/>
		<AD id="double" name="%Double" type="Double" default="1.0"/>
		<AD id="float" name="%Float" type="Float" default="1.0"/>
		<AD id="integer" name="%Integer" type="Integer" default="1"/>
		<AD id="long" name="%Long" type="Long" default="1"/>
		<AD id="short" name="%Short" type="Short" default="1"/>
		<AD id="string" name="%String" type="String" default="test"/>
	</OCD>
	
	<Designate pid="com.acme.ocd1">
		<Object ocdref="ocd1"/>
	</Designate>
	
	<Designate pid="com.acme.ocd2">
		<Object ocdref="ocd2"/>
	</Designate>
</md:MetaData>
